import { EnumModel, EnumValue } from "../models/Enum";

const defaultEnums: EnumValue[] = [
    { type: "muscle", uniqueName: "trapezius", displayName: "Trapezius" },
    { type: "muscle", uniqueName: "shoulders", displayName: "Shoulders" },
    { type: "muscle", uniqueName: "pectorals", displayName: "Pectorals" },
    { type: "muscle", uniqueName: "biceps", displayName: "Biceps" },
    { type: "muscle", uniqueName: "triceps", displayName: "Triceps" },
    { type: "muscle", uniqueName: "forearms", displayName: "Forearms" },
    { type: "muscle", uniqueName: "abs", displayName: "Abs" },
    { type: "muscle", uniqueName: "upperback", displayName: "Upper Back" },
    { type: "muscle", uniqueName: "lats", displayName: "Lats" },
    { type: "muscle", uniqueName: "lowerback", displayName: "Lower Back" },
    { type: "muscle", uniqueName: "quadriceps", displayName: "Quadriceps" },
    { type: "muscle", uniqueName: "adductors", displayName: "Adductors" },
    { type: "muscle", uniqueName: "glutes", displayName: "Glutes" },
    { type: "muscle", uniqueName: "hamstrings", displayName: "Hamstrings" },
    { type: "muscle", uniqueName: "calves", displayName: "Calves" },
    { type: "muscle", uniqueName: "heart", displayName: "Heart" },
    { type: "equipment", uniqueName: "noequipment", displayName: "No Equipment" },
    { type: "equipment", uniqueName: "bench", displayName: "Bench" },
    { type: "equipment", uniqueName: "barbell", displayName: "Barbell" },
    { type: "equipment", uniqueName: "dumbbells", displayName: "Dumbbells" },
    { type: "equipment", uniqueName: "bicycle", displayName: "Bicycle" },
    { type: "equipment", uniqueName: "ellipticalbike", displayName: "Elliptical Bike" },
    { type: "equipment", uniqueName: "treadmill", displayName: "Treadmill" },
    { type: "equipment", uniqueName: "rowingmachine", displayName: "Rowing Machine" },
    { type: "equipment", uniqueName: "stationarybike", displayName: "Stationary Bike" },
    { type: "equipment", uniqueName: "stepper", displayName: "Stepper" },
    { type: "equipment", uniqueName: "stairclimber", displayName: "Stair Climber" },
    { type: "equipment", uniqueName: "jumprope", displayName: "Jump Rope" },
    { type: "equipment", uniqueName: "punchingbag", displayName: "Punching Bag" },
    { type: "equipment", uniqueName: "legpress45", displayName: "45-Degree Leg Press" },
    { type: "equipment", uniqueName: "smithmachine", displayName: "Smith Machine" },
    { type: "equipment", uniqueName: "legextensionmachine", displayName: "Leg Extension Machine" },
    { type: "equipment", uniqueName: "seatedlegpress", displayName: "Seated Leg Press" },
    { type: "equipment", uniqueName: "hacksquatmachine", displayName: "Hack Squat Machine" },
    { type: "equipment", uniqueName: "chestpressmachine", displayName: "Chest Press Machine" },
    { type: "equipment", uniqueName: "pecdeckmachine", displayName: "Pec Deck Machine" },
    { type: "equipment", uniqueName: "flymachine", displayName: "Fly Machine" },
    { type: "equipment", uniqueName: "pullovermachine", displayName: "Pullover Machine" },
    { type: "equipment", uniqueName: "latpulldownnarrow", displayName: "Lat Pulldown Machine (Narrow Grip)" },
    { type: "equipment", uniqueName: "latpulldownwide", displayName: "Lat Pulldown Machine (Wide Grip)" },
    { type: "equipment", uniqueName: "hyperextensionmachine", displayName: "Hyperextension Bench / Back Extension Machine" },
    { type: "equipment", uniqueName: "adductionmachine", displayName: "Adduction Machine" },
    { type: "equipment", uniqueName: "abductionmachine", displayName: "Abduction Machine" },
    { type: "equipment", uniqueName: "assistedcurlmachine", displayName: "Assisted Curl Machine" },
    { type: "equipment", uniqueName: "cablecrossover", displayName: "Cable Crossover Machine" },
    { type: "equipment", uniqueName: "functionaltrainer", displayName: "Functional Trainer / Cable Station" },
    { type: "equipment", uniqueName: "powerrack", displayName: "Power Rack" },
    { type: "equipment", uniqueName: "squatrack", displayName: "Squat Rack" },
    { type: "equipment", uniqueName: "preachercurlbench", displayName: "Preacher Curl Bench" },
    { type: "equipment", uniqueName: "dipstation", displayName: "Dip Station" },
    { type: "equipment", uniqueName: "pullupbar", displayName: "Pull-Up Bar" },
    { type: "equipment", uniqueName: "legcurlmachine", displayName: "Leg Curl Machine" },
    { type: "equipment", uniqueName: "glutekickbackmachine", displayName: "Glute Kickback Machine" },
    { type: "equipment", uniqueName: "hipthrustmachine", displayName: "Hip Thrust Bench / Machine" },
    { type: "equipment", uniqueName: "standingcalfraisemachine", displayName: "Calf Raise Machine (Standing)" },
    { type: "equipment", uniqueName: "seatedcalfraisemachine", displayName: "Seated Calf Raise Machine" },
    { type: "equipment", uniqueName: "shoulderpressmachine", displayName: "Shoulder Press Machine" },
    { type: "equipment", uniqueName: "seatedrowmachine", displayName: "Seated Row Machine" },
    { type: "equipment", uniqueName: "tbarrowmachine", displayName: "T-Bar Row Machine" },
    { type: "equipment", uniqueName: "latrowmachine", displayName: "Lat Row Machine" },
    { type: "equipment", uniqueName: "abcrunchmachine", displayName: "Ab Crunch Machine" },
    { type: "equipment", uniqueName: "obliquetwistmachine", displayName: "Oblique Twist Machine" },
    { type: "equipment", uniqueName: "battleropes", displayName: "Battle Ropes" },
    { type: "equipment", uniqueName: "kettlebells", displayName: "Kettlebells" },
    { type: "equipment", uniqueName: "resistancebands", displayName: "Resistance Bands" },
    { type: "equipment", uniqueName: "medicineball", displayName: "Medicine Ball" },
    { type: "equipment", uniqueName: "weightedvest", displayName: "Weighted Vest" },
    { type: "equipment", uniqueName: "trxtrainer", displayName: "TRX Suspension Trainer" },
    { type: "equipment", uniqueName: "plyobox", displayName: "Plyometric Box" },
    { type: "equipment", uniqueName: "sled", displayName: "Sled / Prowler" },
    { type: "equipment", uniqueName: "landmineattachment", displayName: "Landmine Attachment" },
    { type: "equipment", uniqueName: "horizontallegpress", displayName: "Leg Press (Horizontal)" },
    { type: "equipment", uniqueName: "airbike", displayName: "Air Bike (Assault Bike)" },
    { type: "equipment", uniqueName: "stairsteppermachine", displayName: "Stair Stepper Machine" },
    { type: "equipment", uniqueName: "glutehamdeveloper", displayName: "Glute Ham Developer (GHD)" },
    { type: "feeling", uniqueName: "great", displayName: "Great" },
    { type: "feeling", uniqueName: "good", displayName: "Good" },
    { type: "feeling", uniqueName: "exhausted", displayName: "Exhausted" },
    { type: "feeling", uniqueName: "hurt", displayName: "Hurt" },
    { type: "workoutType", uniqueName: "glutefocus", displayName: "Glute Focus" },
    { type: "workoutType", uniqueName: "legdaytotal", displayName: "Leg Day - Total" },
    { type: "workoutType", uniqueName: "legdayquadriceps", displayName: "Leg Day - Quadriceps Focus" },
    { type: "workoutType", uniqueName: "legdayhamstrings", displayName: "Leg Day - Hamstrings Focus" },
    { type: "workoutType", uniqueName: "restday", displayName: "Rest Day" },
    { type: "workoutType", uniqueName: "cardioday", displayName: "Cardio Day" },
    { type: "workoutType", uniqueName: "upperdaychest", displayName: "Upper Day - Chest Focus" },
    { type: "workoutType", uniqueName: "upperdayarms", displayName: "Upper Day - Arms Focus" },
    { type: "workoutType", uniqueName: "upperdaychestandarms", displayName: "Upper Day - Chest and Arms" },
    { type: "workoutType", uniqueName: "backday", displayName: "Back Day" },
    { type: "workoutType", uniqueName: "backandshouldersday", displayName: "Back and Shoulders Day" },
    { type: "workoutType", uniqueName: "fullbodyday", displayName: "Full Body Day" },
    { type: "workoutType", uniqueName: "coreabsday", displayName: "Core / Abs Day" },
    { type: "workoutType", uniqueName: "functionalmobilityday", displayName: "Functional / Mobility Day" },
    { type: "workoutType", uniqueName: "hiitconditioningday", displayName: "HIIT / Conditioning Day" },
    { type: "workoutType", uniqueName: "shoulderday", displayName: "Shoulder Day" },
    { type: "workoutType", uniqueName: "upperday", displayName: "Upper Day" },
    { type: "workoutType", uniqueName: "activerecoverystretchingday", displayName: "Active Recovery / Stretching Day" }
];

export async function seedEnums() {
    for (const e of defaultEnums) {
        const exists = await EnumModel.findOne({ type: e.type, uniqueName: e.uniqueName });
        if (!exists) {
            await EnumModel.create(e);
        }
    }
}